//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win115.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Win115.Properties.ApiResource", typeof(ApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /get/status/ 的本地化字符串。
        /// </summary>
        internal static string GetQrCodeStatus {
            get {
                return ResourceManager.GetString("GetQrCodeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/authDeviceCode 的本地化字符串。
        /// </summary>
        internal static string OpenAuthDeviceCode {
            get {
                return ResourceManager.GetString("OpenAuthDeviceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/deviceCodeToToken 的本地化字符串。
        /// </summary>
        internal static string OpenDeviceCodeToToken {
            get {
                return ResourceManager.GetString("OpenDeviceCodeToToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/folder/add 的本地化字符串。
        /// </summary>
        internal static string OpenFolderAdd {
            get {
                return ResourceManager.GetString("OpenFolderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/folder/get_info 的本地化字符串。
        /// </summary>
        internal static string OpenFolderGetInfo {
            get {
                return ResourceManager.GetString("OpenFolderGetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/offline/add_task_bt 的本地化字符串。
        /// </summary>
        internal static string OpenOfflineAddTaskBT {
            get {
                return ResourceManager.GetString("OpenOfflineAddTaskBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/offline/add_task_urls 的本地化字符串。
        /// </summary>
        internal static string OpenOfflineAddTaskUrls {
            get {
                return ResourceManager.GetString("OpenOfflineAddTaskUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/offline/clear_task 的本地化字符串。
        /// </summary>
        internal static string OpenOfflineClearTask {
            get {
                return ResourceManager.GetString("OpenOfflineClearTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/offline/del_task 的本地化字符串。
        /// </summary>
        internal static string OpenOfflineDelTask {
            get {
                return ResourceManager.GetString("OpenOfflineDelTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/offline/get_quota_info 的本地化字符串。
        /// </summary>
        internal static string OpenOfflineGetQuotaInfo {
            get {
                return ResourceManager.GetString("OpenOfflineGetQuotaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/offline/get_task_list 的本地化字符串。
        /// </summary>
        internal static string OpenOfflineGetTaskList {
            get {
                return ResourceManager.GetString("OpenOfflineGetTaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/offline/torrent 的本地化字符串。
        /// </summary>
        internal static string OpenOfflineTorrent {
            get {
                return ResourceManager.GetString("OpenOfflineTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/rb/del 的本地化字符串。
        /// </summary>
        internal static string OpenRbDel {
            get {
                return ResourceManager.GetString("OpenRbDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/rb/list 的本地化字符串。
        /// </summary>
        internal static string OpenRbList {
            get {
                return ResourceManager.GetString("OpenRbList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/rb/revert 的本地化字符串。
        /// </summary>
        internal static string OpenRbRevert {
            get {
                return ResourceManager.GetString("OpenRbRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/refreshToken 的本地化字符串。
        /// </summary>
        internal static string OpenRefreshToken {
            get {
                return ResourceManager.GetString("OpenRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/ufile/copy 的本地化字符串。
        /// </summary>
        internal static string OpenUfileCopy {
            get {
                return ResourceManager.GetString("OpenUfileCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/ufile/delete 的本地化字符串。
        /// </summary>
        internal static string OpenUfileDelete {
            get {
                return ResourceManager.GetString("OpenUfileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/ufile/downurl 的本地化字符串。
        /// </summary>
        internal static string OpenUfileDownurl {
            get {
                return ResourceManager.GetString("OpenUfileDownurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/ufile/files 的本地化字符串。
        /// </summary>
        internal static string OpenUfileFiles {
            get {
                return ResourceManager.GetString("OpenUfileFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/ufile/move 的本地化字符串。
        /// </summary>
        internal static string OpenUfileMove {
            get {
                return ResourceManager.GetString("OpenUfileMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/ufile/search 的本地化字符串。
        /// </summary>
        internal static string OpenUfileSearch {
            get {
                return ResourceManager.GetString("OpenUfileSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/ufile/update 的本地化字符串。
        /// </summary>
        internal static string OpenUfileUpdate {
            get {
                return ResourceManager.GetString("OpenUfileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/upload/get_token 的本地化字符串。
        /// </summary>
        internal static string OpenUploadGetToken {
            get {
                return ResourceManager.GetString("OpenUploadGetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/upload/init 的本地化字符串。
        /// </summary>
        internal static string OpenUploadInit {
            get {
                return ResourceManager.GetString("OpenUploadInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/upload/resume 的本地化字符串。
        /// </summary>
        internal static string OpenUploadResume {
            get {
                return ResourceManager.GetString("OpenUploadResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /open/user/info 的本地化字符串。
        /// </summary>
        internal static string OpenUserInfo {
            get {
                return ResourceManager.GetString("OpenUserInfo", resourceCulture);
            }
        }
    }
}
